import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { getServerAuthSession } from "~/server/auth";
import { AgitateSigninModal } from "./_components/agitateSigninModal";
import { SignOutButton } from "./_components/signOutButton";
import { Toast } from "./_components/toast";
import { api } from "~/trpc/server";
import Link from "next/link";

export const metadata = {
  title: "t3 ChatGPT",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  const conversations = await api.conversation.list();
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Toast />
        <TRPCReactProvider>
          <div className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <header className="sticky top-0 px-3 py-2 drop-shadow-lg backdrop-blur-md">
              {session && (
                <div className="ml-auto flex w-fit items-center justify-center gap-4">
                  <p className="text-center text-xl text-white">
                    {session && <span>Logged in as {session.user?.name}</span>}
                  </p>
                  <SignOutButton />
                </div>
              )}
              {!session?.user && <AgitateSigninModal />}
            </header>
            <main className="flex grow gap-6 px-4 py-3">
              {conversations.length && (
                <aside className="text-md flex w-60 flex-col gap-3 text-white">
                  <Link href="/" className="mb-2 text-xl">
                    + Add new chat
                  </Link>
                  {conversations.map((conv) => (
                    <Link
                      key={conv.id}
                      href={`/${conv.id}`}
                      className="truncate text-nowrap rounded-xl px-2 py-1 hover:bg-gray-500"
                    >
                      {conv.title}
                    </Link>
                  ))}
                </aside>
              )}
              {children}
            </main>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
