import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { getServerAuthSession } from "~/server/auth";
import { AgitateSigninModal } from "./_components/agitateSigninModal";
import { SignOutButton } from "./_components/signOutButton";
import { Toast } from "./_components/toast";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Toast />
        <TRPCReactProvider>
          <div className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <header className="sticky top-0 px-3 py-2 drop-shadow-lg backdrop-blur-md">
              {session && (
                <div className="ml-auto flex w-fit items-center justify-center gap-4">
                  <p className="text-center text-xl text-white">
                    {session && <span>Logged in as {session.user?.name}</span>}
                  </p>
                  <SignOutButton />
                </div>
              )}
              {!session?.user && <AgitateSigninModal />}
            </header>
            <main className="flex grow px-4 py-3">{children}</main>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
